### ISSUE TITLE
UI: Figmaレビューを受けての修正

### ISSUE THREAD

**Issue by saku-1101** [saku-1101/stampy#8]
### 🙆‍♀️受け入れ条件
- [ ] TODOが完了されている

### 📝TODO
- [x] フォント試す
- [x] primary button=> background: green, foreground: blackに揃える
- [x] elevationはない方がいいのか？
- [x]  blurを再現する方法をどうにかして見つける（tamaguiで頑張るんじゃなくて普通にstyle属性でいけそう？）つけるとしたら８px位
- [x] キャンセル→いいえに統一（文字KVとかあっても良い
